version: "3"

services:
    web:
        container_name: WebApp
        restart: always
        build: .
        ports:
            - "80:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: DataBase
        image: mongo
        ports:
            - "27017:27017"